pipeline:
  identifier: Build_bhargavamamidi_plugin_sample_1725979068754
  name: Build plugin-sample
  orgIdentifier: default
  projectIdentifier: samplego
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1725979017559
        repoName: bhargavamamidi/plugin-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_go_app
                  name: Build Go App
                  spec:
                    command: |-
                      echo "Welcome to Harness CI.."
                      go build
                      go test
              - step:
                  type: Plugin
                  name: Plugin_2
                  identifier: Plugin_2
                  spec:
                    connectorRef: account.harnessImage
                    image: mamid1b/hello-go-app
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    connectorRef: account.harnessImage
                    image: mamid1b/hello-go-app
                    shell: Sh
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
