pipeline:
  identifier: Build_bhargavamamidi_plugin_sample_1725979068754
  name: Build plugin-sample
  orgIdentifier: default
  projectIdentifier: samplego
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1725979017559
        repoName: bhargavamamidi/plugin-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_go_app
                  name: Build Go App
                  spec:
                    command: |-
                      echo "Welcome to Harness CI.."
                      go build
                      go test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: mamid1b/go-sample-plugin
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
        type: CI
